;;; Streams (SRFI-41 under argyle names).  Run with: test/run streams

(use (argyle) (test check))

(def nats (strm-frm 0))

(check "strm? snil?" '(#t #t #f) (list (strm? nats) (snil? snil) (snil? nats)))
(check "scons scar scdr" '(1 2)
       (let s (scons 1 (scons 2 snil)) (list (scar s) (scar (scdr s)))))
(check "lst->strm strm->lst" '(1 2) (strm->lst (lst->strm '(1 2))))
(check "strm-take" '(0 1 2) (strm->lst (strm-take 3 nats)))
(check "strm-drop" '(5 6) (strm->lst (strm-take 2 (strm-drop 5 nats))))
(check "strm-ref" 7 (strm-ref nats 7))
(check "strm-range" '(2 3 4) (strm->lst (strm-range 2 5)))
(check "strm-map" '(0 10 20) (strm->lst (strm-take 3 (strm-map (\\ * 10 _) nats))))
(check "strm-fltr" '(0 2 4) (strm->lst (strm-take 3 (strm-fltr even? nats))))
(check "strms-fld" 10 (strms-fld + 0 (strm-range 0 5)))
(check "strm-scan" '(0 1 3 6) (strm->lst (strm-scan + 0 (strm-range 1 4))))
(check "strm-zip" '((0 a) (1 b))
       (strm->lst (strm-zip nats (lst->strm '(a b)))))
(check "strm-rev" '(3 2 1) (strm->lst (strm-rev (strm-range 1 4))))
(check "strm-len" 4 (strm-len (strm-range 0 4)))
(check "strm-const" '(x x) (strm->lst (strm-take 2 (strm-const 'x))))
(check "itr" '(1 2 4 8) (strm->lst (strm-take 4 (itr (\\ * 2 _) 1))))
(check "strm-unfld" '(0 1 4)
       (strm->lst (strm-unfld (fn (x) (* x x)) (\\ < _ 3) 1+ 0)))
(check "strm-each" 6 (let n 0 (strm-each (fn (x) (=! n (+ n x))) (strm-range 1 4)) n))
(check "strm-join" '(1 2 3)
       (strm->lst (strm-join (lst->strm (list (strm-range 1 3) (strm-range 3 4))))))
(check "sfn" '(0 1) (strm->lst ((sfn (n) (strm-take n nats)) 2)))
(check "slet" '(3 2 1)
       (strm->lst (slet lp ((n 3)) (if (0? n) snil (scons n (lp (1- n)))))))
(check "strm-of" '(0 1 4 9) (strm->lst (strm-of (* x x) (x in (strm-range 0 4)))))
(check "strm-match" 3 (strm-match (strm-range 1 3) ((a b) (+ a b))))
(check "infinite stream stays lazy" 1000 (strm-ref (strm-map 1+ nats) 999))

(done)
