;;; Streams (SRFI-41 under argyle names).  Run with: test/run streams

(use (argyle) (test check))

(def nats (stream-from 0))

(check "stream? stream-null?" '(#t #t #f) (list (stream? nats) (stream-null? stream-null) (stream-null? nats)))
(check "stream-cons stream-car stream-cdr" '(1 2)
       (let s (stream-cons 1 (stream-cons 2 stream-null)) (list (stream-car s) (stream-car (stream-cdr s)))))
(check "list->stream stream->list" '(1 2) (stream->list (list->stream '(1 2))))
(check "stream-take" '(0 1 2) (stream->list (stream-take 3 nats)))
(check "stream-drop" '(5 6) (stream->list (stream-take 2 (stream-drop 5 nats))))
(check "stream-ref" 7 (stream-ref nats 7))
(check "stream-range" '(2 3 4) (stream->list (stream-range 2 5)))
(check "stream-map" '(0 10 20) (stream->list (stream-take 3 (stream-map (\\ * 10 _) nats))))
(check "stream-filter" '(0 2 4) (stream->list (stream-take 3 (stream-filter even? nats))))
(check "stream-fold" 10 (stream-fold + 0 (stream-range 0 5)))
(check "stream-scan" '(0 1 3 6) (stream->list (stream-scan + 0 (stream-range 1 4))))
(check "stream-zip" '((0 a) (1 b))
       (stream->list (stream-zip nats (list->stream '(a b)))))
(check "stream-reverse" '(3 2 1) (stream->list (stream-reverse (stream-range 1 4))))
(check "stream-length" 4 (stream-length (stream-range 0 4)))
(check "stream-constant" '(x x) (stream->list (stream-take 2 (stream-constant 'x))))
(check "stream-iterate" '(1 2 4 8) (stream->list (stream-take 4 (stream-iterate (\\ * 2 _) 1))))
(check "stream-unfold" '(0 1 4)
       (stream->list (stream-unfold (fn (x) (* x x)) (\\ < _ 3) 1+ 0)))
(check "stream-for-each" 6 (let n 0 (stream-for-each (fn (x) (=! n (+ n x))) (stream-range 1 4)) n))
(check "stream-concat" '(1 2 3)
       (stream->list (stream-concat (list->stream (list (stream-range 1 3) (stream-range 3 4))))))
(check "stream-lambda" '(0 1) (stream->list ((stream-lambda (n) (stream-take n nats)) 2)))
(check "stream-let" '(3 2 1)
       (stream->list (stream-let lp ((n 3)) (if (0? n) stream-null (stream-cons n (lp (1- n)))))))
(check "stream-of" '(0 1 4 9) (stream->list (stream-of (* x x) (x in (stream-range 0 4)))))
(check "stream-match" 3 (stream-match (stream-range 1 3) ((a b) (+ a b))))
(check "infinite stream stays lazy" 1000 (stream-ref (stream-map 1+ nats) 999))

(done)
