(ns (argyle)
    :duplicates (last))

(use (argyle base)
     (argyle match)
     (argyle data)
     (argyle data table)
     (argyle data vec)
     (argyle data queue)
     (argyle data set)
     (argyle generic)
     (argyle generic base)
     (argyle generic coll)
     (argyle loop)
     (argyle nested-loop)
     (argyle conc)
     (argyle reader)
     
     (ice-9 match)
     (ice-9 receive)
     (srfi srfi-45))

(re-export-ns
 (argyle base)
 (argyle match)
 (argyle data)
 (argyle data table)
 (argyle data vec)
 (argyle data queue)
 (argyle data set)
 (argyle generic)
 (argyle generic base)
 (argyle generic coll)
 (argyle loop)
 (argyle nested-loop)
 (argyle conc)
 
 (ice-9 match)
 (ice-9 receive)
 (srfi srfi-45))
