;;; Generic collection functions over lists, vecs, strs, tbls, qs, sets
;;; and streams.  Each keeps the collection's type where that makes sense
;;; (filtering a vec gives a vec); map over a table gives a list.
(ns (argyle generic coll)
  :export (map filter reduce cpy clr!))
(use (argyle base)
     (argyle generic)
     (argyle data table)
     (argyle data vec)
     (argyle data queue)
     (argyle data set)
     ((srfi srfi-1) :select ((map . lst-map)
                             (filter . lst-filter)
                             (reduce . lst-reduce))))

(gen map lst-map)
(xtnd map (f <fn> v <vec>) (vec-map f v))
(xtnd map (f <fn> s <str> . rst) (apply string-map f s rst))
(xtnd map (f <fn> t <table>) (table-map->list f t))
(xtnd map (f <fn> q <queue>) (list->queue (lst-map f (queue->list q))))
(xtnd map (f <fn> s <set>) (apply set (lst-map f (elements s))))
(xtnd map (f <fn> s <stream>) (strm-map f s))

(gen filter lst-filter)
(xtnd filter (f <fn> v <vec>) (list->vec (lst-filter f (vec->list v))))
(xtnd filter (f <fn> s <str>) (string-filter f s))
(xtnd filter (f <fn> t <table>)
  (ret t* (make-table)
    (table-for-each (fn (k v) (when (f k v) (t* k v))) t)))
(xtnd filter (f <fn> q <queue>) (list->queue (lst-filter f (queue->list q))))
(xtnd filter (f <fn> s <set>) (apply set (lst-filter f (elements s))))
(xtnd filter (f <fn> s <stream>) (strm-fltr f s))

;;; (reduce f ridentity coll), as SRFI-1's reduce.
(gen reduce lst-reduce)
(xtnd reduce (f <fn> init <any> v <vec>) (lst-reduce f init (vec->list v)))
(xtnd reduce (f <fn> init <any> s <str>) (lst-reduce f init (string->list s)))
(xtnd reduce (f <fn> init <any> q <queue>) (lst-reduce f init (queue->list q)))
(xtnd reduce (f <fn> init <any> s <set>) (lst-reduce f init (elements s)))
(xtnd reduce (f <fn> init <any> s <stream>) (lst-reduce f init (strm->lst s)))

(gen cpy list-copy)
(xtnd cpy (s <str>) (string-copy s))
(xtnd cpy (v <vec>) (vec-copy v))
(xtnd cpy (t <table>) (ret t* (make-table) (table-for-each t* t)))
(xtnd cpy (q <queue>) (list->queue (queue->list q)))
(xtnd cpy (s <set>) (apply set (elements s)))

(gen clr! (fn (lst) (set-cdr! lst '())))
(xtnd clr! (t <table>) (table-clear! t))
(xtnd clr! (q <queue>) (queue-clear! q))
(xtnd clr! (s <set>) (set-clear! s))
