;;; Generic collection functions over lists, vecs, strs, tbls, qs, sets
;;; and streams.  Each keeps the collection's type where that makes sense
;;; (filtering a vec gives a vec); map over a tbl gives a list.
(ns (argyle generic coll)
  :export (map filter reduce cpy clr!))
(use (argyle base)
     (argyle generic)
     (argyle data tbl)
     (argyle data vec)
     (argyle data q)
     (argyle data set)
     ((srfi srfi-1) :select ((map . lst-map)
                             (filter . lst-filter)
                             (reduce . lst-reduce))))

(gen map lst-map)
(xtnd map (f <fn> v <vec>) (vec-map f v))
(xtnd map (f <fn> s <str> . rst) (apply string-map f s rst))
(xtnd map (f <fn> t <tbl>) (tbl-map->lst f t))
(xtnd map (f <fn> q <q>) (lst->q (lst-map f (q->lst q))))
(xtnd map (f <fn> s <set>) (apply set (lst-map f (elements s))))
(xtnd map (f <fn> s <strm>) (strm-map f s))

(gen filter lst-filter)
(xtnd filter (f <fn> v <vec>) (lst->vec (lst-filter f (vec->lst v))))
(xtnd filter (f <fn> s <str>) (string-filter f s))
(xtnd filter (f <fn> t <tbl>)
  (ret t* (mke-tbl)
    (tbl-each (fn (k v) (when (f k v) (t* k v))) t)))
(xtnd filter (f <fn> q <q>) (lst->q (lst-filter f (q->lst q))))
(xtnd filter (f <fn> s <set>) (apply set (lst-filter f (elements s))))
(xtnd filter (f <fn> s <strm>) (strm-fltr f s))

;;; (reduce f ridentity coll), as SRFI-1's reduce.
(gen reduce lst-reduce)
(xtnd reduce (f <fn> init <any> v <vec>) (lst-reduce f init (vec->lst v)))
(xtnd reduce (f <fn> init <any> s <str>) (lst-reduce f init (string->list s)))
(xtnd reduce (f <fn> init <any> q <q>) (lst-reduce f init (q->lst q)))
(xtnd reduce (f <fn> init <any> s <set>) (lst-reduce f init (elements s)))
(xtnd reduce (f <fn> init <any> s <strm>) (lst-reduce f init (strm->lst s)))

(gen cpy list-copy)
(xtnd cpy (s <str>) (string-copy s))
(xtnd cpy (v <vec>) (vec-cpy v))
(xtnd cpy (t <tbl>) (ret t* (mke-tbl) (tbl-each t* t)))
(xtnd cpy (q <q>) (%mke-q (q-len q) (q-hd q) (q-tl q)))
(xtnd cpy (s <set>) (apply set (elements s)))

(gen clr! (fn (lst) (set-cdr! lst '())))
(xtnd clr! (t <tbl>) (tbl-clr! t))
(xtnd clr! (q <q>) (q-hd! q '()) (q-tl! q '()) (q-len! q 0))
(xtnd clr! (s <set>) (hash-clear! (set-t s)))
