;;; Generic collection functions over lists, vecs, strings, tables, queues, sets
;;; and streams.  Each keeps the collection's type where that makes sense
;;; (filtering a vec gives a vec); map over a table gives a list.
(ns (argyle generic coll)
  :export (map filter reduce copy clear!))
(use (argyle base)
     (argyle generic)
     (argyle data table)
     (argyle data vec)
     (argyle data queue)
     (argyle data set)
     ((srfi srfi-1) :select ((map . lst-map)
                             (filter . lst-filter)
                             (reduce . lst-reduce))))

(generic map lst-map)
(extend map (f <fn> v <vec>) (vec-map f v))
(extend map (f <fn> s <str> . rst) (apply string-map f s rst))
(extend map (f <fn> t <table>) (table-map->list f t))
(extend map (f <fn> q <queue>) (list->queue (lst-map f (queue->list q))))
(extend map (f <fn> s <set>) (apply set (lst-map f (elements s))))
(extend map (f <fn> s <stream>) (stream-map f s))

(generic filter lst-filter)
(extend filter (f <fn> v <vec>) (list->vec (lst-filter f (vec->list v))))
(extend filter (f <fn> s <str>) (string-filter f s))
(extend filter (f <fn> t <table>)
  (ret t* (make-table)
    (table-for-each (fn (k v) (when (f k v) (t* k v))) t)))
(extend filter (f <fn> q <queue>) (list->queue (lst-filter f (queue->list q))))
(extend filter (f <fn> s <set>) (apply set (lst-filter f (elements s))))
(extend filter (f <fn> s <stream>) (stream-filter f s))

;;; (reduce f ridentity coll), as SRFI-1's reduce.
(generic reduce lst-reduce)
(extend reduce (f <fn> init <any> v <vec>) (lst-reduce f init (vec->list v)))
(extend reduce (f <fn> init <any> s <str>) (lst-reduce f init (string->list s)))
(extend reduce (f <fn> init <any> q <queue>) (lst-reduce f init (queue->list q)))
(extend reduce (f <fn> init <any> s <set>) (lst-reduce f init (elements s)))
(extend reduce (f <fn> init <any> s <stream>) (lst-reduce f init (stream->list s)))

(generic copy list-copy)
(extend copy (s <str>) (string-copy s))
(extend copy (v <vec>) (vec-copy v))
(extend copy (t <table>) (ret t* (make-table) (table-for-each t* t)))
(extend copy (q <queue>) (list->queue (queue->list q)))
(extend copy (s <set>) (apply set (elements s)))

(generic clear! (fn (lst) (set-cdr! lst '())))
(extend clear! (t <table>) (table-clear! t))
(extend clear! (q <queue>) (queue-clear! q))
(extend clear! (s <set>) (set-clear! s))
